# Generated by Django 3.0.4 on 2020-04-29 07:57

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_pk', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='object pk')),
                ('template_name', models.CharField(max_length=255)),
                ('template_data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='template rendering data')),
                ('changes', django.contrib.postgres.fields.jsonb.JSONField(blank=True, verbose_name='change diff')),
                ('remote_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='remote IP')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='contenttypes.ContentType', verbose_name='content type')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='actionlogs', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'log action',
                'verbose_name_plural': 'log actions',
                'ordering': ['-created_at'],
            },
        ),
    ]
