# Generated by Django 3.1.7 on 2021-03-16 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210209_0637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='user',
            name='settings',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
