BANKING_ACCOUNT_NUMBER = r"^\d{5,13}$"
MOBILEPHONE_NUMBER = r"^\d{3}-\d{4}-\d{4}$"
TELEPHONE_NUMBER = r"\d{1,10}$"

CSV_TELEPHONE_NUMBER = TELEPHONE_NUMBER

POSTAL_CODE = r"^(?:\d{3}-\d{4})$"

CUSTOMER_ID = r"DFFC\d{10}"
