# Generated by Django 3.0.4 on 2020-04-08 05:12

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import hyakumori_crm.crm.models.customer


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_auto_20200408_0104'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='address',
            field=django.contrib.postgres.fields.jsonb.JSONField(db_index=True, default=hyakumori_crm.crm.models.customer.DefaultCustomer.address),
        ),
        migrations.AddField(
            model_name='contact',
            name='email',
            field=models.EmailField(default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='mobilephone',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='name_kana',
            field=django.contrib.postgres.fields.jsonb.JSONField(db_index=True, default=hyakumori_crm.crm.models.customer.DefaultCustomer.name_kana),
        ),
        migrations.AddField(
            model_name='contact',
            name='name_kanji',
            field=django.contrib.postgres.fields.jsonb.JSONField(db_index=True, default=hyakumori_crm.crm.models.customer.DefaultCustomer.name_kanji),
        ),
        migrations.AddField(
            model_name='contact',
            name='postal_code',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='telephone',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
    ]
