# Generated by Django 3.0.4 on 2020-04-15 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_fix_django_guardian_20200414_1710'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='archive',
            options={'permissions': [('manage_archive', 'All permissions for customer')]},
        ),
        migrations.RemoveField(
            model_name='archive',
            name='author',
        ),
        migrations.RemoveField(
            model_name='archive',
            name='editor',
        ),
        migrations.RemoveField(
            model_name='archivecustomer',
            name='author',
        ),
        migrations.RemoveField(
            model_name='archivecustomer',
            name='editor',
        ),
        migrations.RemoveField(
            model_name='archiveforest',
            name='author',
        ),
        migrations.RemoveField(
            model_name='archiveforest',
            name='editor',
        ),
        migrations.RemoveField(
            model_name='attachment',
            name='author',
        ),
        migrations.RemoveField(
            model_name='attachment',
            name='editor',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='author',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='editor',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='author',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='editor',
        ),
        migrations.RemoveField(
            model_name='customercontact',
            name='author',
        ),
        migrations.RemoveField(
            model_name='customercontact',
            name='editor',
        ),
        migrations.RemoveField(
            model_name='forest',
            name='author',
        ),
        migrations.RemoveField(
            model_name='forest',
            name='editor',
        ),
        migrations.RemoveField(
            model_name='forestcustomer',
            name='author',
        ),
        migrations.RemoveField(
            model_name='forestcustomer',
            name='editor',
        ),
    ]
