# Generated by Django 3.0.4 on 2020-04-28 02:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0007_alter_customer_contact_rels_20200421_0419'),
    ]

    operations = [
        migrations.AddField(
            model_name='archive',
            name='author',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='archive',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='archive',
            name='future_action',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='archive',
            name='location',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='archive',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='archive',
            name='archive_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='object_id',
            field=models.CharField(max_length=255),
        ),
    ]
