# Generated by Django 3.0.4 on 2020-05-02 11:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('crm', '0009_messagetemplate'),
    ]

    operations = [
        migrations.RunSQL(
            sql=["""
                DO $$
                BEGIN
                    IF EXISTS(SELECT *
                        FROM information_schema.columns
                        WHERE table_name='crm_forest' and column_name='tag')
                    THEN
                        ALTER TABLE crm_forest RENAME COLUMN "tag" TO "tags";
                    END IF;
                END $$;
                """],
            reverse_sql=["""
                DO $$
                BEGIN
                    IF EXISTS(SELECT *
                        FROM information_schema.columns
                        WHERE table_name='crm_forest' and column_name='tags')
                    THEN
                        ALTER TABLE crm_forest RENAME COLUMN "tags" TO "tag";
                    END IF;
                END $$;
             """]
        ),
    ]
