# Generated by Django 3.0.4 on 2020-05-07 07:03

import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_rename_forest_tags_key_20200502_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='archive',
            name='tags',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
    ]
