# Generated by Django 3.0.4 on 2020-07-02 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0014_postal_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archive',
            name='future_action',
            field=models.TextField(null=True),
        ),
    ]
