# Generated by Django 3.0.4 on 2020-07-23 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0016_remove_origin_forestcustomercontact_relations"),
    ]

    operations = [
        migrations.RunSQL(
            """update crm_forest
set contracts = jsonb_build_array(
    contracts->0,
    contracts->-1 || jsonb_build_object(
        'status',
        case
        when contracts->-1->>'status' in ('未契約', '期限切')
        then '未加入'
        when contracts->-1->>'status' in ('契約済')
        then '加入'
        else contracts->-1->>'status'
        end
    )
),
updated_at=now();"""
        )
    ]
