# Generated by Django 3.0.10 on 2020-12-24 02:40

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0017_update_fsc_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='forest',
            name='location',
            field=django.contrib.gis.db.models.fields.PolygonField(null=True, srid=4326),
        ),
    ]
