# Generated by Django 3.0.10 on 2021-01-04 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0018_forest_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forest',
            old_name='location',
            new_name='geom',
        ),
    ]
