# Generated by Django 3.0.10 on 2021-01-04 04:57

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0020_auto_20210104_0357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forest',
            name='geom',
            field=django.contrib.gis.db.models.fields.PolygonField(null=True, srid=2447),
        ),
    ]
