# Generated by Django 3.0.10 on 2021-01-05 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0022_auto_20210104_0654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forest',
            name='geodata',
        ),
    ]
