# Generated by Django 3.0.10 on 2021-01-05 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0023_remove_forest_geodata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forest',
            old_name='geom',
            new_name='geodata',
        ),
    ]
