# Generated by Django 3.1.7 on 2021-03-16 15:48

import django.core.serializers.json
from django.db import migrations, models
import hyakumori_crm.crm.models.customer
import hyakumori_crm.crm.models.forest


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0024_auto_20210105_0143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archive',
            name='attributes',
            field=models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
        migrations.AlterField(
            model_name='archive',
            name='tags',
            field=models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
        migrations.AlterField(
            model_name='archivecustomer',
            name='attributes',
            field=models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
        migrations.AlterField(
            model_name='archivecustomercontact',
            name='attributes',
            field=models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
        migrations.AlterField(
            model_name='archiveforest',
            name='attributes',
            field=models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
        migrations.AlterField(
            model_name='archiveuser',
            name='attributes',
            field=models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='attributes',
            field=models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
        migrations.AlterField(
            model_name='contact',
            name='address',
            field=models.JSONField(db_index=True, default=hyakumori_crm.crm.models.customer.DefaultCustomer.address),
        ),
        migrations.AlterField(
            model_name='contact',
            name='attributes',
            field=models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
        migrations.AlterField(
            model_name='contact',
            name='contact_info',
            field=models.JSONField(default=hyakumori_crm.crm.models.customer.DefaultContact.contact_info),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name_kana',
            field=models.JSONField(db_index=True, default=hyakumori_crm.crm.models.customer.DefaultCustomer.name_kana),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name_kanji',
            field=models.JSONField(db_index=True, default=hyakumori_crm.crm.models.customer.DefaultCustomer.name_kanji),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.JSONField(db_index=True, default=hyakumori_crm.crm.models.customer.DefaultCustomer.address),
        ),
        migrations.AlterField(
            model_name='customer',
            name='attributes',
            field=models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
        migrations.AlterField(
            model_name='customer',
            name='banking',
            field=models.JSONField(default=hyakumori_crm.crm.models.customer.DefaultCustomer.banking),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name_kana',
            field=models.JSONField(db_index=True, default=hyakumori_crm.crm.models.customer.DefaultCustomer.name_kana),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name_kanji',
            field=models.JSONField(db_index=True, default=hyakumori_crm.crm.models.customer.DefaultCustomer.name_kanji),
        ),
        migrations.AlterField(
            model_name='customer',
            name='tags',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='customercontact',
            name='attributes',
            field=models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
        migrations.AlterField(
            model_name='forest',
            name='attributes',
            field=models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
        migrations.AlterField(
            model_name='forest',
            name='cadastral',
            field=models.JSONField(db_index=True, default=hyakumori_crm.crm.models.forest.DefaultForest.cadastral),
        ),
        migrations.AlterField(
            model_name='forest',
            name='contracts',
            field=models.JSONField(db_index=True, default=hyakumori_crm.crm.models.forest.DefaultForest.contracts, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
        migrations.AlterField(
            model_name='forest',
            name='forest_attributes',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='forest',
            name='land_attributes',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='forest',
            name='owner',
            field=models.JSONField(db_index=True, default=hyakumori_crm.crm.models.forest.DefaultForest.owner),
        ),
        migrations.AlterField(
            model_name='forest',
            name='tags',
            field=models.JSONField(default=hyakumori_crm.crm.models.forest.DefaultForest.tags),
        ),
        migrations.AlterField(
            model_name='forestcustomer',
            name='attributes',
            field=models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
        migrations.AlterField(
            model_name='forestcustomercontact',
            name='attributes',
            field=models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
        migrations.AlterField(
            model_name='messagetemplate',
            name='attributes',
            field=models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
        migrations.AlterField(
            model_name='postalhistory',
            name='attributes',
            field=models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
        migrations.AlterField(
            model_name='postalhistory',
            name='tags',
            field=models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
        migrations.AlterField(
            model_name='postalhistorycustomer',
            name='attributes',
            field=models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
        migrations.AlterField(
            model_name='postalhistorycustomercontact',
            name='attributes',
            field=models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
        migrations.AlterField(
            model_name='postalhistoryforest',
            name='attributes',
            field=models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
        migrations.AlterField(
            model_name='postalhistoryuser',
            name='attributes',
            field=models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
    ]
