query getForestList($filter: ForestListFilterInput!){
  list_forests(data: $filter) {
    ok
    total
    forests {
      id
      internal_id
      geodata
      attributes
      cadastral
      owner
      contracts
      tags
      land_attributes
      forest_attributes
      geodata
      updated_by {
        id
      }
      updated_at
      created_at
    }
  }
}
