"""
Django settings for hyakumori_crm project.

Generated by 'django-admin startproject' using Django 3.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os
import urllib.parse
from distutils.util import strtobool

import dj_database_url
from django.utils.translation import gettext_lazy as _
from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY", "change this please")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = strtobool(os.getenv("DEBUG", "no"))

ALLOWED_HOSTS = ["localhost"]


# Application definition
STATIC_ROOT = os.path.join(
    BASE_DIR, os.getenv("STATIC_DIR", "hyakumori_crm/static/hyakumori_crm/dist")
)

if os.getenv("STATIC_DIR") == "":
    STATIC_ROOT = None

static_app = []
if not STATIC_ROOT:
    static_app = ["hyakumori_crm.static"]

orjson_experiment = []
if not DEBUG:
    orjson_experiment = ["hyakumori_crm.core"]

INSTALLED_APPS = [
    *orjson_experiment,
    "whitenoise.runserver_nostatic",
    *static_app,  # this need high priority due to some override commands
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.staticfiles",
    "ariadne.contrib.django",
    # ─── THIRD PARTIES APP ──────────────────────────────────────────────────────────
    "django_extensions",
    "rest_framework",
    "behaviors.apps.BehaviorsConfig",
    # ─── HYAKUMORI APPS ─────────────────────────────────────────────────────────────
    "hyakumori_crm.users",
    "hyakumori_crm.crm",
    "hyakumori_crm.customer",
    "hyakumori_crm.forest",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "hyakumori_crm.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [STATIC_ROOT] if STATIC_ROOT else [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "hyakumori_crm.wsgi.application"


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    "default": dict(
        **dj_database_url.parse(
            urllib.parse.quote(os.environ.get("DATABASE_URL"), ":/@")
        ),
        TEST={"NAME": "hyakumori_crm_test"}
    )
}

# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = "ja"

TIME_ZONE = "UTC"

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"
STATIC_URL = "/"

AUTH_USER_MODEL = "users.User"

LANGUAGES = [("ja", _("Japan"))]

LOCALE_PATHS = [os.path.join(BASE_DIR, "hyakumori_crm", "locale")]
