# Generated by Django 3.0.4 on 2020-06-18 09:19

import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Oauth",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "attributes",
                    django.contrib.postgres.fields.jsonb.JSONField(
                        default=dict,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                    ),
                ),
                ("access_token", models.CharField(max_length=255)),
                ("team_id", models.CharField(db_index=True, max_length=11)),
                ("team_name", models.CharField(max_length=255)),
                ("scope", models.CharField(max_length=255)),
                (
                    "incoming_webhook",
                    django.contrib.postgres.fields.jsonb.JSONField(
                        null=True,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                    ),
                ),
                ("bot_user_id", models.CharField(max_length=11)),
                ("authed_user_id", models.CharField(max_length=11)),
            ],
            options={"abstract": False},
        ),
    ]
