# Generated by Django 3.0.10 on 2020-12-21 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contracttype',
            options={'ordering': ['created_at'], 'verbose_name': 'contract type', 'verbose_name_plural': 'contract type'},
        ),
    ]
